apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-agent-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: external-agent-secrets
    creationPolicy: Owner
  data:
    - secretKey: A2A_BEARER_TOKEN
      remoteRef:
        key: ica4aa/shared-dev/agents/<AGENT_NAME>/a2a-auth
    - secretKey: VITE_A2A_BEARER_TOKEN
      remoteRef:
        key: ica4aa/shared-dev/agents/<AGENT_NAME>/a2a-auth
