apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agent-<AGENT_NAME>
resources:
  - namespace.yaml
  - ../../../../gitops/templates/external-agent-v2
  - externalsecret.yaml
images:
  - name: ghcr.io/ica4aa/external-agent
    newName: ""
    newTag: ""
  - name: ghcr.io/ica4aa/external-agent-frontend
    newName: ""
    newTag: ""
commonLabels:
  app.kubernetes.io/part-of: ica4aa-external-agents
  ica4aa.io/managed: "true"
patches:
  - path: ingress-patch.yaml
  - path: deployment-backend-patch.yaml
  - path: deployment-frontend-patch.yaml
  - path: configmap-patch.yaml
  - path: serviceaccount-patch.yaml
replacements:
  - source:
      kind: ServiceAccount
      name: external-agent
      fieldPath: metadata.annotations.[eks.amazonaws.com/role-arn]
    targets:
      - select:
          kind: Deployment
          name: external-agent
        fieldPaths:
          - spec.template.metadata.annotations.[eks.amazonaws.com/role-arn]
        options:
          create: true
      - select:
          kind: Deployment
          name: external-agent-frontend
        fieldPaths:
          - spec.template.metadata.annotations.[eks.amazonaws.com/role-arn]
        options:
          create: true
